### ISSUE TITLE
您好, 从搜索引擎找到了一篇您的文章 有些问题想要请教一下, 不知道是否方便

### ISSUE THREAD

**Issue by KSroido** [hexclover/turing-project#1]
https://0xclover.com/2023/05/miui-wallet-in-global-roms/
我是从这篇文章来的
如果方便的话可以加个TG或者QQ, 想请教一些简单的问题, 主要是解决问题的思路上 想要请教一下 
具体操作我这边已经成功操作了, 可以正常使用钱包目前
如果可以的话非常感谢

**Comment by KSroido** [comment]
其实之前在CTF群里面也看到过一两次您的博客, 但是一直没找到机会请教QWQ

**Comment by hexclover** [comment]
邮件回你啦，你主页上写的 gmail 邮箱
